# Generated by Django 5.2.6 on 2025-09-09 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hold_token', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('row', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
            options={
                'unique_together': {('venue', 'section', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False)),
                ('hold_until', models.DateTimeField(blank=True, null=True)),
                ('hold_token', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.seat')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.tickettype')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'is_sold'], name='events_inve_event_i_741319_idx'), models.Index(fields=['hold_until'], name='events_inve_hold_un_997c13_idx')],
                'unique_together': {('event', 'seat')},
            },
        ),
    ]
